## np.unique

In [2]:
import numpy as np

np.unique([1, 1, 2, 2, 3, 3])

array([1, 2, 3])

In [3]:
np.unique(np.array([[1, 0, 0], [1, 0, 0], [2, 3, 4]]))

array([0, 1, 2, 3, 4])

In [6]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
u, indices = np.unique(a, return_index=True)

print(u)
print(indices)
print(a[indices])

['a' 'b' 'c']
[0 1 3]
['a' 'b' 'c']


In [9]:
a = np.array([1, 2, 6, 4, 2, 3, 2])
u, indices = np.unique(a, return_inverse=True)
print(u)
print(indices)
print(u[indices])

[1 2 3 4 6]
[0 1 4 3 1 2 1]
[1 2 6 4 2 3 2]


In [10]:
a = np.array([1, 2, 6, 4, 2, 3, 2])
values, counts = np.unique(a, return_counts=True)
print(values)
print(counts)
print(np.repeat(values, counts))

[1 2 3 4 6]
[1 3 1 1 1]
[1 2 2 2 3 4 6]


## np.concatenate

In [1]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[7, 8], [9, 10], [11, 12]])

np.concatenate((a, b), axis=0)

array([[ 1,  2],
       [ 3,  4],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [2]:
np.concatenate((a, b.T), axis=1)

array([[ 1,  2,  7,  9, 11],
       [ 3,  4,  8, 10, 12]])

In [3]:
np.concatenate((a, b), axis=None)

array([ 1,  2,  3,  4,  7,  8,  9, 10, 11, 12])