In [1]:
import numpy as np

In [2]:
a = np.array([[1,2], [3,4]])
a.flatten()

array([1, 2, 3, 4])

Parameters
order{‘C’, ‘F’, ‘A’, ‘K’}, optional  The default is ‘C’.

‘C’ means to flatten in row-major (C-style) order.  
‘F’ means to flatten in column-major (Fortran- style) order.  
‘A’ means to flatten in column-major order if a is Fortran contiguous in memory, row-major order otherwise.   
‘K’ means to flatten a in the order the elements occur in memory.  

In [3]:
a.flatten('F')

array([1, 3, 2, 4])

In [4]:
a.flatten('C')

array([1, 2, 3, 4])

In [5]:
a.flatten('A')

array([1, 2, 3, 4])

In [6]:
a.flatten('K')

array([1, 2, 3, 4])